package com.pandafit.core.database.catalog

data class CatalogExercise(
    val nom: String,
    val type: String,
    val muscles: List<String>,
    val equipment: List<String>,
)

object MuscuCatalog {
    val exercises: List<CatalogExercise> = listOf(
        CatalogExercise("Développé couché barre", "Pluri", listOf("Pectoraux", "Triceps", "Deltoïde antérieur"), listOf("Barre", "Banc plat", "Rack")),
        CatalogExercise("Développé couché haltères", "Pluri", listOf("Pectoraux", "Triceps", "Deltoïde antérieur"), listOf("Haltères", "Banc plat")),
        CatalogExercise("Développé couché incliné barre", "Pluri", listOf("Pectoraux (chef claviculaire)", "Triceps", "Deltoïde antérieur"), listOf("Barre", "Banc incliné", "Rack")),
        CatalogExercise("Développé couché incliné haltères", "Pluri", listOf("Pectoraux (chef claviculaire)", "Triceps", "Deltoïde antérieur"), listOf("Haltères", "Banc incliné")),
        CatalogExercise("Développé couché décliné barre", "Pluri", listOf("Pectoraux (chef sternal)", "Triceps", "Deltoïde antérieur"), listOf("Barre", "Banc décliné", "Rack")),
        CatalogExercise("Développé couché décliné haltères", "Pluri", listOf("Pectoraux (chef sternal)", "Triceps", "Deltoïde antérieur"), listOf("Haltères", "Banc décliné")),
        CatalogExercise("Écarté couché haltères", "Mono", listOf("Pectoraux", "Deltoïde antérieur"), listOf("Haltères", "Banc plat")),
        CatalogExercise("Écarté incliné haltères", "Mono", listOf("Pectoraux (chef claviculaire)", "Deltoïde antérieur"), listOf("Haltères", "Banc incliné")),
        CatalogExercise("Écarté décliné haltères", "Mono", listOf("Pectoraux (chef sternal)", "Deltoïde antérieur"), listOf("Haltères", "Banc décliné")),
        CatalogExercise("Crossover câbles (poulie haute)", "Mono", listOf("Pectoraux", "Deltoïde antérieur"), listOf("Câble / Poulie")),
        CatalogExercise("Crossover câbles (poulie basse)", "Mono", listOf("Pectoraux (chef claviculaire)", "Deltoïde antérieur"), listOf("Câble / Poulie")),
        CatalogExercise("Pec deck / Butterfly machine", "Mono", listOf("Pectoraux", "Deltoïde antérieur"), listOf("Machine pec deck")),
        CatalogExercise("Dips (poitrine)", "Pluri", listOf("Pectoraux", "Triceps", "Deltoïde antérieur"), listOf("Barres parallèles")),
        CatalogExercise("Pompes", "Pluri", listOf("Pectoraux", "Triceps", "Deltoïde antérieur", "Serratus"), listOf("Poids de corps")),
        CatalogExercise("Pompes larges", "Pluri", listOf("Pectoraux", "Triceps", "Deltoïde antérieur"), listOf("Poids de corps")),
        CatalogExercise("Pompes diamant", "Pluri", listOf("Triceps", "Pectoraux", "Deltoïde antérieur"), listOf("Poids de corps")),
        CatalogExercise("Développé couché Smith machine", "Pluri", listOf("Pectoraux", "Triceps", "Deltoïde antérieur"), listOf("Barre", "Banc plat", "Rack", "Smith machine")),
        CatalogExercise("Pull-over haltère", "Mono", listOf("Pectoraux (grand)", "Grand dorsal", "Triceps (longue portion)"), listOf("Haltère", "Banc plat")),
        CatalogExercise("Pull-over à la poulie", "Mono", listOf("Pectoraux (grand)", "Grand dorsal", "Triceps (longue portion)"), listOf("Câble / Poulie")),
        CatalogExercise("Traction pronation (pull-up)", "Pluri", listOf("Grand dorsal", "Biceps", "Trapèze", "Rhomboïdes"), listOf("Barre de traction")),
        CatalogExercise("Traction supination (chin-up)", "Pluri", listOf("Grand dorsal", "Biceps", "Trapèze", "Rhomboïdes"), listOf("Barre de traction")),
        CatalogExercise("Traction neutre", "Pluri", listOf("Grand dorsal", "Biceps", "Trapèze", "Rhomboïdes"), listOf("Barre de traction")),
        CatalogExercise("Lat pulldown pronation", "Pluri", listOf("Grand dorsal", "Biceps", "Trapèze", "Rhomboïdes"), listOf("Câble / Poulie haute", "Barre de tirage")),
        CatalogExercise("Lat pulldown supination", "Pluri", listOf("Grand dorsal", "Biceps", "Trapèze", "Rhomboïdes"), listOf("Câble / Poulie haute", "Barre de tirage")),
        CatalogExercise("Lat pulldown neutre", "Pluri", listOf("Grand dorsal", "Biceps", "Trapèze"), listOf("Câble / Poulie haute")),
        CatalogExercise("Rowing barre (Bent-over row)", "Pluri", listOf("Grand dorsal", "Trapèze", "Rhomboïdes", "Biceps", "Érecteurs du rachis"), listOf("Barre", "Rack")),
        CatalogExercise("Rowing haltère unilatéral", "Pluri", listOf("Grand dorsal", "Trapèze", "Rhomboïdes", "Biceps"), listOf("Haltère", "Banc / appui")),
        CatalogExercise("Rowing câble assis (prise serrée)", "Pluri", listOf("Grand dorsal", "Trapèze", "Rhomboïdes", "Biceps"), listOf("Câble / Poulie basse")),
        CatalogExercise("Rowing câble assis (prise large)", "Pluri", listOf("Grand dorsal", "Trapèze", "Rhomboïdes", "Biceps"), listOf("Câble / Poulie basse")),
        CatalogExercise("Rowing T-bar", "Pluri", listOf("Grand dorsal", "Trapèze", "Rhomboïdes", "Biceps", "Érecteurs du rachis"), listOf("Barre T-bar", "Rack")),
        CatalogExercise("Rowing Pendlay", "Pluri", listOf("Grand dorsal", "Trapèze", "Rhomboïdes", "Biceps", "Érecteurs du rachis"), listOf("Barre", "Rack")),
        CatalogExercise("Rowing Yates (barre EZ)", "Pluri", listOf("Grand dorsal", "Trapèze", "Rhomboïdes", "Biceps"), listOf("Barre EZ", "Rack")),
        CatalogExercise("Rowing machine (Hammer Strength)", "Pluri", listOf("Grand dorsal", "Trapèze", "Rhomboïdes", "Biceps"), listOf("Machine Hammer Strength")),
        CatalogExercise("Face pull câble", "Pluri", listOf("Deltoïde postérieur", "Trapèze", "Rhomboïdes", "Infra-épineux"), listOf("Câble / Poulie")),
        CatalogExercise("Tirage nuque câble", "Pluri", listOf("Grand dorsal", "Trapèze", "Biceps", "Rhomboïdes"), listOf("Câble / Poulie haute", "Barre de tirage")),
        CatalogExercise("Good morning", "Pluri", listOf("Érecteurs du rachis", "Ischio-jambiers", "Fessiers"), listOf("Barre")),
        CatalogExercise("Hyperextension (GHD)", "Pluri", listOf("Érecteurs du rachis", "Fessiers", "Ischio-jambiers"), listOf("GHD / Banc à lombaires")),
        CatalogExercise("Deadlift roumain câble", "Pluri", listOf("Ischio-jambiers", "Fessiers", "Érecteurs du rachis"), listOf("Câble / Poulie basse")),
        CatalogExercise("Shrug barre", "Mono", listOf("Trapèze supérieur"), listOf("Barre")),
        CatalogExercise("Shrug haltères", "Mono", listOf("Trapèze supérieur"), listOf("Haltères")),
        CatalogExercise("Shrug machine", "Mono", listOf("Trapèze supérieur"), listOf("Machine")),
        CatalogExercise("Shrug câble", "Mono", listOf("Trapèze supérieur"), listOf("Câble / Poulie")),
        CatalogExercise("Développé militaire barre", "Pluri", listOf("Deltoïde antérieur", "Deltoïde médial", "Triceps", "Trapèze"), listOf("Barre", "Rack")),
        CatalogExercise("Développé militaire haltères", "Pluri", listOf("Deltoïde antérieur", "Deltoïde médial", "Triceps", "Trapèze"), listOf("Haltères")),
        CatalogExercise("Développé Arnold", "Pluri", listOf("Deltoïde antérieur", "Deltoïde médial", "Triceps"), listOf("Haltères")),
        CatalogExercise("Développé épaules machine", "Pluri", listOf("Deltoïde antérieur", "Deltoïde médial", "Triceps"), listOf("Machine épaules")),
        CatalogExercise("Développé épaules Smith machine", "Pluri", listOf("Deltoïde antérieur", "Deltoïde médial", "Triceps"), listOf("Barre", "Smith machine")),
        CatalogExercise("Élévation latérale haltères", "Mono", listOf("Deltoïde médial", "Trapèze supérieur"), listOf("Haltères")),
        CatalogExercise("Élévation latérale câble", "Mono", listOf("Deltoïde médial", "Trapèze supérieur"), listOf("Câble / Poulie")),
        CatalogExercise("Élévation latérale machine", "Mono", listOf("Deltoïde médial", "Trapèze supérieur"), listOf("Machine élévations latérales")),
        CatalogExercise("Élévation frontale barre", "Mono", listOf("Deltoïde antérieur", "Deltoïde médial"), listOf("Barre")),
        CatalogExercise("Élévation frontale haltères", "Mono", listOf("Deltoïde antérieur", "Deltoïde médial"), listOf("Haltères")),
        CatalogExercise("Élévation frontale câble", "Mono", listOf("Deltoïde antérieur", "Deltoïde médial"), listOf("Câble / Poulie")),
        CatalogExercise("Oiseau haltères (rear delt fly)", "Mono", listOf("Deltoïde postérieur", "Trapèze", "Rhomboïdes"), listOf("Haltères", "Banc incliné")),
        CatalogExercise("Oiseau câble (rear delt fly)", "Mono", listOf("Deltoïde postérieur", "Trapèze", "Rhomboïdes"), listOf("Câble / Poulie")),
        CatalogExercise("Reverse pec deck", "Mono", listOf("Deltoïde postérieur", "Trapèze", "Rhomboïdes"), listOf("Machine pec deck (inversée)")),
        CatalogExercise("Upright row barre", "Pluri", listOf("Deltoïde médial", "Trapèze", "Biceps"), listOf("Barre")),
        CatalogExercise("Upright row haltères", "Pluri", listOf("Deltoïde médial", "Trapèze", "Biceps"), listOf("Haltères")),
        CatalogExercise("Upright row câble", "Pluri", listOf("Deltoïde médial", "Trapèze", "Biceps"), listOf("Câble / Poulie")),
        CatalogExercise("Cuban press", "Pluri", listOf("Infra-épineux", "Deltoïde postérieur", "Trapèze"), listOf("Haltères")),
        CatalogExercise("Curl barre droite", "Mono", listOf("Biceps brachial", "Brachial", "Brachioradial"), listOf("Barre droite")),
        CatalogExercise("Curl barre EZ", "Mono", listOf("Biceps brachial", "Brachial", "Brachioradial"), listOf("Barre EZ")),
        CatalogExercise("Curl haltères debout", "Mono", listOf("Biceps brachial", "Brachial", "Brachioradial"), listOf("Haltères")),
        CatalogExercise("Curl haltères alterné", "Mono", listOf("Biceps brachial", "Brachial", "Brachioradial"), listOf("Haltères")),
        CatalogExercise("Curl haltères concentré", "Mono", listOf("Biceps brachial", "Brachial"), listOf("Haltère", "Banc")),
        CatalogExercise("Curl marteau haltères", "Mono", listOf("Brachial", "Brachioradial", "Biceps brachial"), listOf("Haltères")),
        CatalogExercise("Curl marteau câble", "Mono", listOf("Brachial", "Brachioradial", "Biceps brachial"), listOf("Câble / Poulie")),
        CatalogExercise("Curl incliné haltères", "Mono", listOf("Biceps brachial (longue portion)", "Brachial"), listOf("Haltères", "Banc incliné")),
        CatalogExercise("Curl pupitre (Scott curl)", "Mono", listOf("Biceps brachial (courte portion)", "Brachial"), listOf("Haltères", "Banc Scott / Pupitre")),
        CatalogExercise("Curl câble poulie basse", "Mono", listOf("Biceps brachial", "Brachial", "Brachioradial"), listOf("Câble / Poulie basse")),
        CatalogExercise("Curl câble poulie haute", "Mono", listOf("Biceps brachial", "Brachial"), listOf("Câble / Poulie haute")),
        CatalogExercise("Curl Zottman", "Mono", listOf("Biceps brachial", "Brachioradial", "Brachial"), listOf("Haltères")),
        CatalogExercise("Curl spider", "Mono", listOf("Biceps brachial (courte portion)", "Brachial"), listOf("Haltères", "Banc incliné")),
        CatalogExercise("Curl machine", "Mono", listOf("Biceps brachial", "Brachial"), listOf("Machine curl")),
        CatalogExercise("Curl à 21", "Mono", listOf("Biceps brachial", "Brachial", "Brachioradial"), listOf("Haltères / Barre")),
        CatalogExercise("Développé couché prise serrée", "Pluri", listOf("Triceps", "Pectoraux", "Deltoïde antérieur"), listOf("Barre", "Banc plat")),
        CatalogExercise("Barre au front (Skull crusher)", "Mono", listOf("Triceps"), listOf("Barre", "Banc plat")),
        CatalogExercise("Barre au front EZ", "Mono", listOf("Triceps"), listOf("Barre EZ", "Banc plat")),
        CatalogExercise("Extension triceps câble (corde)", "Mono", listOf("Triceps"), listOf("Câble / Poulie", "Corde")),
        CatalogExercise("Extension triceps câble (barre droite)", "Mono", listOf("Triceps"), listOf("Câble / Poulie", "Barre droite")),
        CatalogExercise("Extension triceps câble (prise inversée)", "Mono", listOf("Triceps (longue portion)"), listOf("Câble / Poulie")),
        CatalogExercise("Kick-back haltère", "Mono", listOf("Triceps"), listOf("Haltère")),
        CatalogExercise("Kick-back câble", "Mono", listOf("Triceps"), listOf("Câble / Poulie")),
        CatalogExercise("Extension triceps overhead haltère", "Mono", listOf("Triceps (longue portion)"), listOf("Haltère")),
        CatalogExercise("Extension triceps overhead câble", "Mono", listOf("Triceps (longue portion)"), listOf("Câble / Poulie")),
        CatalogExercise("Extension triceps overhead barre EZ", "Mono", listOf("Triceps (longue portion)"), listOf("Barre EZ")),
        CatalogExercise("Dips banc (triceps)", "Pluri", listOf("Triceps", "Pectoraux", "Deltoïde antérieur"), listOf("Banc")),
        CatalogExercise("Triceps machine", "Mono", listOf("Triceps"), listOf("Machine triceps")),
        CatalogExercise("JM press", "Pluri", listOf("Triceps", "Pectoraux"), listOf("Barre", "Banc plat")),
        CatalogExercise("Squat barre haute", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers", "Érecteurs du rachis", "Adducteurs"), listOf("Barre", "Rack")),
        CatalogExercise("Squat barre basse", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers", "Érecteurs du rachis", "Adducteurs"), listOf("Barre", "Rack")),
        CatalogExercise("Squat avant (Front squat)", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers", "Érecteurs du rachis"), listOf("Barre", "Rack")),
        CatalogExercise("Squat gobelet", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers"), listOf("Haltère / Kettlebell")),
        CatalogExercise("Squat Smith machine", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers"), listOf("Smith machine")),
        CatalogExercise("Squat hack machine", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers"), listOf("Machine hack squat")),
        CatalogExercise("Hack squat barre", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers"), listOf("Barre")),
        CatalogExercise("Leg press", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers"), listOf("Machine leg press")),
        CatalogExercise("Fente barre", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers", "Adducteurs"), listOf("Barre", "Rack")),
        CatalogExercise("Fente haltères", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers", "Adducteurs"), listOf("Haltères")),
        CatalogExercise("Fente marchée", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers", "Adducteurs"), listOf("Haltères")),
        CatalogExercise("Fente bulgare (split squat)", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers"), listOf("Haltères", "Banc / appui")),
        CatalogExercise("Step-up haltères", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers"), listOf("Haltères", "Banc / step")),
        CatalogExercise("Leg extension machine", "Mono", listOf("Quadriceps"), listOf("Machine leg extension")),
        CatalogExercise("Sissy squat", "Mono", listOf("Quadriceps"), listOf("Poids de corps / Barre")),
        CatalogExercise("Zercher squat", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers", "Érecteurs du rachis"), listOf("Barre")),
        CatalogExercise("Squat sur une jambe (pistol squat)", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers"), listOf("Poids de corps")),
        CatalogExercise("Soulevé de terre conventionnel", "Pluri", listOf("Érecteurs du rachis", "Fessiers", "Ischio-jambiers", "Quadriceps", "Trapèze"), listOf("Barre", "Rack")),
        CatalogExercise("Soulevé de terre sumo", "Pluri", listOf("Fessiers", "Ischio-jambiers", "Adducteurs", "Érecteurs du rachis", "Quadriceps"), listOf("Barre", "Rack")),
        CatalogExercise("Soulevé de terre roumain", "Pluri", listOf("Ischio-jambiers", "Fessiers", "Érecteurs du rachis"), listOf("Barre")),
        CatalogExercise("Soulevé de terre jambes tendues", "Pluri", listOf("Ischio-jambiers", "Fessiers", "Érecteurs du rachis"), listOf("Barre")),
        CatalogExercise("Soulevé de terre pieds-mains (Trap bar)", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers", "Érecteurs du rachis", "Trapèze"), listOf("Trap bar / Hex bar")),
        CatalogExercise("Leg curl couché machine", "Mono", listOf("Ischio-jambiers"), listOf("Machine leg curl")),
        CatalogExercise("Leg curl assis machine", "Mono", listOf("Ischio-jambiers"), listOf("Machine leg curl")),
        CatalogExercise("Leg curl câble debout", "Mono", listOf("Ischio-jambiers"), listOf("Câble / Poulie")),
        CatalogExercise("Nordic curl", "Mono", listOf("Ischio-jambiers"), listOf("Poids de corps / Partenaire")),
        CatalogExercise("Hip thrust barre", "Pluri", listOf("Fessiers", "Ischio-jambiers"), listOf("Barre", "Banc / appui")),
        CatalogExercise("Hip thrust machine", "Pluri", listOf("Fessiers", "Ischio-jambiers"), listOf("Machine hip thrust")),
        CatalogExercise("Glute bridge", "Pluri", listOf("Fessiers", "Ischio-jambiers"), listOf("Poids de corps / Haltère")),
        CatalogExercise("Donkey kick câble", "Mono", listOf("Fessiers"), listOf("Câble / Poulie")),
        CatalogExercise("Hip abduction machine", "Mono", listOf("Fessiers (moyen et petit)", "TFL"), listOf("Machine abduction")),
        CatalogExercise("Hip adduction machine", "Mono", listOf("Adducteurs"), listOf("Machine adduction")),
        CatalogExercise("Cable pull-through", "Pluri", listOf("Fessiers", "Ischio-jambiers", "Érecteurs du rachis"), listOf("Câble / Poulie basse")),
        CatalogExercise("Squat sumo haltère", "Pluri", listOf("Fessiers", "Adducteurs", "Quadriceps", "Ischio-jambiers"), listOf("Haltère")),
        CatalogExercise("Curtsy lunge", "Pluri", listOf("Fessiers (moyen)", "Quadriceps", "Adducteurs"), listOf("Haltères / Barre")),
        CatalogExercise("Mollets debout machine", "Mono", listOf("Gastrocnémien", "Soléaire"), listOf("Machine mollets debout")),
        CatalogExercise("Mollets assis machine", "Mono", listOf("Soléaire", "Gastrocnémien"), listOf("Machine mollets assis")),
        CatalogExercise("Mollets debout barre", "Mono", listOf("Gastrocnémien", "Soléaire"), listOf("Barre", "Rack")),
        CatalogExercise("Mollets debout haltère unilatéral", "Mono", listOf("Gastrocnémien", "Soléaire"), listOf("Haltère")),
        CatalogExercise("Mollets au leg press", "Mono", listOf("Gastrocnémien", "Soléaire"), listOf("Machine leg press")),
        CatalogExercise("Dorsiflexion poids de corps", "Mono", listOf("Tibial antérieur"), listOf("Poids de corps")),
        CatalogExercise("Crunch", "Mono", listOf("Droit abdominal", "Obliques"), listOf("Poids de corps / Tapis")),
        CatalogExercise("Crunch machine", "Mono", listOf("Droit abdominal", "Obliques"), listOf("Machine crunch")),
        CatalogExercise("Crunch câble", "Mono", listOf("Droit abdominal", "Obliques"), listOf("Câble / Poulie")),
        CatalogExercise("Relevé de jambes suspendu", "Mono", listOf("Iliopsoas", "Droit abdominal"), listOf("Barre de traction")),
        CatalogExercise("Relevé de jambes sol", "Mono", listOf("Iliopsoas", "Droit abdominal"), listOf("Poids de corps / Tapis")),
        CatalogExercise("Ab wheel (roue abdominale)", "Pluri", listOf("Droit abdominal", "Obliques", "Grand dorsal", "Triceps"), listOf("Ab wheel")),
        CatalogExercise("Dragon flag", "Pluri", listOf("Droit abdominal", "Obliques", "Grand dorsal"), listOf("Banc décliné")),
        CatalogExercise("Planche (gainage)", "Mono", listOf("Transverse", "Droit abdominal", "Obliques", "Érecteurs du rachis"), listOf("Poids de corps / Tapis")),
        CatalogExercise("Planche latérale", "Mono", listOf("Obliques", "Transverse"), listOf("Poids de corps / Tapis")),
        CatalogExercise("Russian twist", "Mono", listOf("Obliques", "Droit abdominal"), listOf("Poids de corps / Tapis")),
        CatalogExercise("Mountain climber", "Pluri", listOf("Droit abdominal", "Obliques", "Iliopsoas", "Quadriceps"), listOf("Poids de corps / Tapis")),
        CatalogExercise("Wood chop câble", "Pluri", listOf("Obliques", "Droit abdominal", "Grand dorsal", "Épaules"), listOf("Câble / Poulie")),
        CatalogExercise("Pallof press câble", "Mono", listOf("Transverse", "Obliques", "Droit abdominal"), listOf("Câble / Poulie")),
        CatalogExercise("Rollout sur genoux", "Pluri", listOf("Droit abdominal", "Grand dorsal", "Triceps"), listOf("Ab wheel")),
        CatalogExercise("Windshield wiper", "Mono", listOf("Obliques", "Droit abdominal"), listOf("Poids de corps / Tapis")),
        CatalogExercise("Hollow hold", "Mono", listOf("Droit abdominal", "Transverse", "Iliopsoas"), listOf("Poids de corps / Tapis")),
        CatalogExercise("V-up", "Mono", listOf("Droit abdominal", "Iliopsoas"), listOf("Poids de corps / Tapis")),
        CatalogExercise("Toes to bar", "Pluri", listOf("Droit abdominal", "Iliopsoas", "Grand dorsal"), listOf("Barre de traction")),
        CatalogExercise("Ab slide machine", "Mono", listOf("Droit abdominal", "Obliques"), listOf("Machine abdominaux")),
        CatalogExercise("Curl avant-bras barre (prise pronation)", "Mono", listOf("Extenseurs du carpe", "Brachioradial"), listOf("Barre droite")),
        CatalogExercise("Curl avant-bras barre (prise supination)", "Mono", listOf("Fléchisseurs du carpe", "Brachioradial"), listOf("Barre droite")),
        CatalogExercise("Curl avant-bras haltère", "Mono", listOf("Fléchisseurs du carpe", "Brachioradial"), listOf("Haltère")),
        CatalogExercise("Farmer's walk", "Pluri", listOf("Avant-bras (grip)", "Trapèze", "Fessiers", "Quadriceps", "Érecteurs du rachis"), listOf("Haltères lourds")),
        CatalogExercise("Plate pinch", "Mono", listOf("Avant-bras (grip)"), listOf("Disques de fonte")),
        CatalogExercise("Wrist roller", "Mono", listOf("Fléchisseurs du carpe", "Extenseurs du carpe"), listOf("Wrist roller")),
        CatalogExercise("Reverse curl barre", "Mono", listOf("Brachioradial", "Extenseurs du carpe", "Biceps brachial"), listOf("Barre droite")),
        CatalogExercise("Arraché (Snatch)", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers", "Érecteurs du rachis", "Trapèze", "Deltoïdes"), listOf("Barre olympique", "Rack", "Plateforme")),
        CatalogExercise("Épaulé-jeté (Clean & Jerk)", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers", "Érecteurs du rachis", "Trapèze", "Deltoïdes"), listOf("Barre olympique", "Rack", "Plateforme")),
        CatalogExercise("Power clean", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers", "Érecteurs du rachis", "Trapèze"), listOf("Barre olympique", "Plateforme")),
        CatalogExercise("Power snatch", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers", "Érecteurs du rachis", "Trapèze"), listOf("Barre olympique", "Plateforme")),
        CatalogExercise("Kettlebell swing", "Pluri", listOf("Fessiers", "Ischio-jambiers", "Érecteurs du rachis", "Épaules"), listOf("Kettlebell")),
        CatalogExercise("Turkish get-up", "Pluri", listOf("Épaules", "Fessiers", "Abdominaux", "Quadriceps"), listOf("Kettlebell / Haltère")),
        CatalogExercise("Clean tiré (High pull)", "Pluri", listOf("Trapèze", "Fessiers", "Quadriceps", "Ischio-jambiers", "Deltoïdes"), listOf("Barre olympique", "Plateforme")),
        CatalogExercise("Landmine press", "Pluri", listOf("Deltoïde antérieur", "Pectoraux", "Triceps"), listOf("Barre", "Landmine")),
        CatalogExercise("Landmine row", "Pluri", listOf("Grand dorsal", "Trapèze", "Biceps", "Rhomboïdes"), listOf("Barre", "Landmine")),
        CatalogExercise("Landmine squat", "Pluri", listOf("Quadriceps", "Fessiers", "Ischio-jambiers"), listOf("Barre", "Landmine")),
    )
}
